### ISSUE TITLE
Support for starlettes request state property

### ISSUE THREAD

**Issue by FirstKlaas** [taoufik07/responder#382]
Current version of starlettes request object has a state property (which is a dict), where you can store useful data. Either by a middleware or a route decorator. Responder has a dependency to starlette 0.10.7 and lacks of a similar feature. This feature is extremely helpful, when propagating information through request chain or giving access to certain functions.

**Usecase A:**
In a rest API (with a database backend) each call needs to be secured. Most requests also need to check for certain rights. Based on a bearer token, provided with the request, I need to lookup the user and store it somewhere, so that all middleware components or routes can use it in their logic.

**Usecase B**
Pagination of a get ressource has some defaults regarding the maximum number of items returned. This can be configured. But how to access the data within the route class in a pythonic way? State information at request level are super helpful.

My suggestion would be to either implement something similar directly in the Responder request class or update the dependency and add a property to expose the starlette request state.

**Comment by taoufik07** [comment]
Thanks @FirstKlaas , yep I think it can be useful, for now we can expose the starlette state and let it do the work for us.

Thanks for pointing out to the version, I've upgraded to 0.11.* but maybe Kenneth didn't release, anyway master is now using starlette 0.12.* and we've moved to asgi 3 :tada:.

If you have some time I would be happy if you can make a PR :D

**Comment by taoufik07** [comment]
closed via #385
