### ISSUE TITLE
Broken release (internal conflict)

### ISSUE THREAD

**Issue by waghanza** [taoufik07/responder#401]
Hi @taoufik07,

With the implementation in https://github.com/the-benchmarker/web-frameworks/blob/master/python/responder/server.py, I have an error for `responder` **2.0.0**

The following error occurs :
~~~
ImportError: cannot import name 'Templates' from 'responder.templates' (/usr/local/lib/python3.7/site-packages/responder/templates/__init__.py)
~~~

The package **templates** is in conflict.

There is a module defined in https://github.com/taoufik07/responder/blob/master/responder/ext/graphql/templates.py and in https://github.com/taoufik07/responder/blob/master/responder/templates.py.

Regards,

**Comment by taoufik07** [comment]
Thanks @waghanza, some untracked files created the conflicts, v2.0.2 should be fine

**Comment by waghanza** [comment]
@taoufik07 still have the issue on https://github.com/the-benchmarker/web-frameworks/pull/1907
