### ISSUE TITLE
Args 'title', 'version' and 'openapi' ignored.

### ISSUE THREAD

**Issue by tomasssalles** [taoufik07/responder#407]
Commit 'd24b921cdc4e19f062f8ae3dad01a5eaa69180dd' caused args `title`, `version` and `openapi` of the `API` intializer to be ignored. The OpenAPISchema is now initialized with hard-coded values which were probably meant as default fall-backs.

```
title="Web Service",
version="1.0",
openapi="3.0.2",
```

**Comment by StevenAvelino24** [comment]
Since #411 was merged, we can close this issue 👍
