### ISSUE TITLE
Make server restart on file changes in code

### ISSUE THREAD

**Issue by mpaepper** [taoufik07/responder#409]
Is it possible to have responder restart on file changes?

Something like --reload flag in gunicorn?

**Comment by whippiii** [comment]
`uvicorn` is already installed as a dependency. So, taking the basic example from the [docs](https://responder.readthedocs.io/en/latest/):
```python
import responder

api = responder.API()

@api.route("/{greeting}")
async def greet_world(req, resp, *, greeting):
    resp.text = f"{greeting}, world!"

if __name__ == '__main__':
    api.run()
```
Let's say this module's name is `main.py`. You can enable auto-reload by running:
```bash
uvicorn main:api --reload
```

**Comment by mpaepper** [comment]
Awesome, thanks for pointing that out!
