### ISSUE TITLE
What exactly the third argument of decorated function with api.route does?

### ISSUE THREAD

**Issue by tomoyks** [taoufik07/responder#417]
Here is an example code of responder.
```python
import responder
api = responder.API()

@api.route("/{greeting}")
async def greet_world(req, resp, *, greeting):
    resp.text = f"{greeting}, world!"

if __name__ == '__main__':
    api.run()
```

I wonder what is the role of third argument asterisk.

I think here is [the line which call route function](https://github.com/taoufik07/responder/blob/109937adf41492b1a6fc826fb294cf7b32cbd99c/responder/routes.py#L137) but I couldn't find any part which give value corresponds third augment asterisk.

Please tell me the role of third argument of decorated function with api.route does.
Thank you.

**Comment by taoufik07** [comment]
Docs: https://www.python.org/dev/peps/pep-3102/

Using `*` tells python to only accept keyword-only arguments after it (`*`) 

```python
>>> def func(a, b, *, c):
        print(a, b, c)
>>> func(1, 2, 3) # Will raise an error
>>> func(1, 2, c=3) # 1, 2, 3
```

**Comment by tomoyks** [comment]
Now it becomes clear, thank you for answering!
