### ISSUE TITLE
Stop stream response if client disconnects

### ISSUE THREAD

**Issue by JacobHenner** [taoufik07/responder#423]
If a client disconnects from a stream, responder continues to execute the function providing the stream. This is undesirable in certain situations (e.g. if there's a long-running loop, rather than a fixed amount of computation). Instead, responder should stop the function if the client disconnects.

This behavior can be observed in Flask.

**Comment by taoufik07** [comment]
Thanks @JacobHenner, looks like it was fixed in https://github.com/encode/starlette/pull/839, I guess we only need to upgrade starlette
