### ISSUE TITLE
Missing uvloop on default setup

### ISSUE THREAD

**Issue by waghanza** [taoufik07/responder#449]
Hi,

I can see that `uvicorn` is required in https://github.com/taoufik07/responder/blob/b32eda70d2a36b4014388d6eb226448ef0591d33/setup.py#L26

However, starting from `uvicorn` `0.12` it setup process has changed 
https://github.com/encode/uvicorn/blob/master/CHANGELOG.md#changed-1

Regards,

/cc @tomchristie @taoufik07 @kennethreitz42 

----

I had to force `uvicorn[standard]` in my **requirements.tx**t in https://github.com/the-benchmarker/web-frameworks/pull/3364 to have `uvloop`

The start command is
```
gunicorn  \
  --log-level warning  \
  --bind 0.0.0.0:3000  \
  --reuse-port  \
  --workers $(nproc)  \
  --worker-class uvicorn.workers.UvicornWorker \
    server:app
```

**Comment by taoufik07** [comment]
Thank you @waghanza !

I've made a PR https://github.com/taoufik07/responder/pull/450, is it possible to check if it fixes the problem for you ?

**Comment by waghanza** [comment]
seems ok for me https://the-benchmarker.semaphoreci.com/jobs/dd99b167-c088-4516-9224-ad69f34924ed @taoufik07 

could you ping me when release ?

**Comment by taoufik07** [comment]
@waghanza Thank you, A new release v20.7 has been issued !
